# Settings for the download of the owl files
download:
  timeout: 120 # in seconds
  allowed_hosts: ["gitlab.com","localhost","raw.githubusercontent.com"]
  allowed_extensions: [".ttl",".owl",".rdf"]
